#!/usr/bin/env python3
"""Extract the exact release's Changesets changelog section."""
from pathlib import Path
import re
import sys
from importlib.util import module_from_spec, spec_from_file_location

spec = spec_from_file_location('release_version', Path(__file__).with_name('sync-version.py'))
versions = module_from_spec(spec)
spec.loader.exec_module(versions)
version = versions.version()


def section(path):
    text = path.read_text()
    match = re.search(r'^## ' + re.escape(version) + r'\s*\n([\s\S]*?)(?=^## |\Z)', text, re.M)
    if not match or not match[1].strip():
        raise ValueError(f'Missing changelog for {version}: {path}')
    return match[1].strip()


if sys.argv[1:] == ['version-pr']:
    print(f'''## Summary

Version the desktop app, CLI and website to {version}. Merging this PR starts the platform builds and publishes v{version} only when signing and corresponding-source checks pass.

```text
Changesets → synchronized package/Cargo versions → platform builds → GitHub release
```

## Evidence

Generated by `bun run release:version`; CI is dispatched against this branch's exact commit. Platform builds and publication run after merge.
''')
    for package in versions.PACKAGES:
        path = versions.ROOT / package
        print(f'### {path.parent.name} {version}\n\n{section(path.with_name("CHANGELOG.md"))}\n')
    print('''## Merge Danger

**Door:** one-way after publication; reverting this PR does not remove published artifacts.

**Blast radius:** desktop downloads, CLI versions and website release metadata. Missing signing credentials or source coverage stops publication.

Refs CNV-13

Created with GPT-6.1 Sol in T3 Code.''')
elif not sys.argv[1:]:
    print(section(versions.ROOT / 'apps/desktop/CHANGELOG.md'))
else:
    sys.exit('usage: notes.py [version-pr]')
