/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppShellRouteImport } from './routes/_app/_shell'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppShellAccountRouteImport } from './routes/_app/_shell/account'
import { Route as AppSignInIndexRouteImport } from './routes/_app/sign-in/index'
import { Route as AppSignInCheckEmailRouteImport } from './routes/_app/sign-in/check-email'
import { Route as AppShellDashboardIndexRouteImport } from './routes/_app/_shell/dashboard/index'
import { Route as AppShellDashboardApiRouteImport } from './routes/_app/_shell/dashboard/api'
import { Route as AppShellDashboardBillingRouteImport } from './routes/_app/_shell/dashboard/billing'
import { Route as AppShellDashboardLicensesRouteImport } from './routes/_app/_shell/dashboard/licenses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRoute = AppShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppShellAccountRoute = AppShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppShellRoute,
} as any)
const AppSignInIndexRoute = AppSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInCheckEmailRoute = AppSignInCheckEmailRouteImport.update({
  id: '/sign-in/check-email',
  path: '/sign-in/check-email',
  getParentRoute: () => AppRoute,
} as any)
const AppShellDashboardIndexRoute = AppShellDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellDashboardApiRoute = AppShellDashboardApiRouteImport.update({
  id: '/dashboard/api',
  path: '/dashboard/api',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellDashboardBillingRoute =
  AppShellDashboardBillingRouteImport.update({
    id: '/dashboard/billing',
    path: '/dashboard/billing',
    getParentRoute: () => AppShellRoute,
  } as any)
const AppShellDashboardLicensesRoute =
  AppShellDashboardLicensesRouteImport.update({
    id: '/dashboard/licenses',
    path: '/dashboard/licenses',
    getParentRoute: () => AppShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/account': typeof AppShellAccountRoute
  '/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/sign-in/': typeof AppSignInIndexRoute
  '/dashboard/api': typeof AppShellDashboardApiRoute
  '/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/dashboard/': typeof AppShellDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof AppPrivacyRoute
  '/terms': typeof AppTermsRoute
  '/account': typeof AppShellAccountRoute
  '/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/sign-in': typeof AppSignInIndexRoute
  '/dashboard/api': typeof AppShellDashboardApiRoute
  '/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/dashboard': typeof AppShellDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_shell': typeof AppShellRouteWithChildren
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/_shell/account': typeof AppShellAccountRoute
  '/_app/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/_app/sign-in/': typeof AppSignInIndexRoute
  '/_app/_shell/dashboard/api': typeof AppShellDashboardApiRoute
  '/_app/_shell/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/_app/_shell/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/_app/_shell/dashboard/': typeof AppShellDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/sign-in/check-email'
    | '/sign-in/'
    | '/dashboard/api'
    | '/dashboard/billing'
    | '/dashboard/licenses'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/account'
    | '/sign-in/check-email'
    | '/sign-in'
    | '/dashboard/api'
    | '/dashboard/billing'
    | '/dashboard/licenses'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_shell'
    | '/_app/privacy'
    | '/_app/terms'
    | '/_app/_shell/account'
    | '/_app/sign-in/check-email'
    | '/_app/sign-in/'
    | '/_app/_shell/dashboard/api'
    | '/_app/_shell/dashboard/billing'
    | '/_app/_shell/dashboard/licenses'
    | '/_app/_shell/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/account': {
      id: '/_app/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppShellAccountRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/sign-in/': {
      id: '/_app/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AppSignInIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in/check-email': {
      id: '/_app/sign-in/check-email'
      path: '/sign-in/check-email'
      fullPath: '/sign-in/check-email'
      preLoaderRoute: typeof AppSignInCheckEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_shell/dashboard/': {
      id: '/_app/_shell/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppShellDashboardIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/api': {
      id: '/_app/_shell/dashboard/api'
      path: '/dashboard/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof AppShellDashboardApiRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/billing': {
      id: '/_app/_shell/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AppShellDashboardBillingRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/licenses': {
      id: '/_app/_shell/dashboard/licenses'
      path: '/dashboard/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof AppShellDashboardLicensesRouteImport
      parentRoute: typeof AppShellRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellAccountRoute: typeof AppShellAccountRoute
  AppShellDashboardApiRoute: typeof AppShellDashboardApiRoute
  AppShellDashboardBillingRoute: typeof AppShellDashboardBillingRoute
  AppShellDashboardLicensesRoute: typeof AppShellDashboardLicensesRoute
  AppShellDashboardIndexRoute: typeof AppShellDashboardIndexRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellAccountRoute: AppShellAccountRoute,
  AppShellDashboardApiRoute: AppShellDashboardApiRoute,
  AppShellDashboardBillingRoute: AppShellDashboardBillingRoute,
  AppShellDashboardLicensesRoute: AppShellDashboardLicensesRoute,
  AppShellDashboardIndexRoute: AppShellDashboardIndexRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

interface AppRouteChildren {
  AppShellRoute: typeof AppShellRouteWithChildren
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTermsRoute: typeof AppTermsRoute
  AppSignInCheckEmailRoute: typeof AppSignInCheckEmailRoute
  AppSignInIndexRoute: typeof AppSignInIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShellRoute: AppShellRouteWithChildren,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTermsRoute: AppTermsRoute,
  AppSignInCheckEmailRoute: AppSignInCheckEmailRoute,
  AppSignInIndexRoute: AppSignInIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
