/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppShellRouteImport } from './routes/_app/_shell'
import { Route as AppDeviceRouteImport } from './routes/_app/device'
import { Route as SiteChangelogRouteImport } from './routes/_site/changelog'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteDownloadRouteImport } from './routes/_site/download'
import { Route as SiteFormatsRouteImport } from './routes/_site/formats'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as CheckoutDesktopRouteImport } from './routes/checkout/desktop'
import { Route as CheckoutProRouteImport } from './routes/checkout/pro'
import { Route as UpdatesManifestDotjsonRouteImport } from './routes/updates/manifest[.]json'
import { Route as AppShellAccountRouteImport } from './routes/_app/_shell/account'
import { Route as AppCheckoutSuccessRouteImport } from './routes/_app/checkout/success'
import { Route as AppSignInIndexRouteImport } from './routes/_app/sign-in/index'
import { Route as AppSignInCheckEmailRouteImport } from './routes/_app/sign-in/check-email'
import { Route as AppSignInVerifyRouteImport } from './routes/_app/sign-in/verify'
import { Route as AppSignInVerifyEmailRouteImport } from './routes/_app/sign-in/verify-email'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDeviceCloudRouteImport } from './routes/api/device/cloud'
import { Route as ApiDeviceLicenseRouteImport } from './routes/api/device/license'
import { Route as ApiDeviceSignOutRouteImport } from './routes/api/device/sign-out'
import { Route as ApiDeviceTokenRouteImport } from './routes/api/device/token'
import { Route as AppShellDashboardIndexRouteImport } from './routes/_app/_shell/dashboard/index'
import { Route as AppShellDashboardApiRouteImport } from './routes/_app/_shell/dashboard/api'
import { Route as AppShellDashboardBillingRouteImport } from './routes/_app/_shell/dashboard/billing'
import { Route as AppShellDashboardLicensesRouteImport } from './routes/_app/_shell/dashboard/licenses'
import { Route as AppShellDashboardApiConvertRouteImport } from './routes/_app/_shell/dashboard/api_.convert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRoute = AppShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AppRoute,
} as any)
const AppDeviceRoute = AppDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any)
const SiteChangelogRoute = SiteChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDownloadRoute = SiteDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFormatsRoute = SiteFormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const CheckoutDesktopRoute = CheckoutDesktopRouteImport.update({
  id: '/checkout/desktop',
  path: '/checkout/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProRoute = CheckoutProRouteImport.update({
  id: '/checkout/pro',
  path: '/checkout/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesManifestDotjsonRoute = UpdatesManifestDotjsonRouteImport.update({
  id: '/updates/manifest.json',
  path: '/updates/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellAccountRoute = AppShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppShellRoute,
} as any)
const AppCheckoutSuccessRoute = AppCheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInIndexRoute = AppSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInCheckEmailRoute = AppSignInCheckEmailRouteImport.update({
  id: '/sign-in/check-email',
  path: '/sign-in/check-email',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInVerifyRoute = AppSignInVerifyRouteImport.update({
  id: '/sign-in/verify',
  path: '/sign-in/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInVerifyEmailRoute = AppSignInVerifyEmailRouteImport.update({
  id: '/sign-in/verify-email',
  path: '/sign-in/verify-email',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceCloudRoute = ApiDeviceCloudRouteImport.update({
  id: '/api/device/cloud',
  path: '/api/device/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceLicenseRoute = ApiDeviceLicenseRouteImport.update({
  id: '/api/device/license',
  path: '/api/device/license',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceSignOutRoute = ApiDeviceSignOutRouteImport.update({
  id: '/api/device/sign-out',
  path: '/api/device/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceTokenRoute = ApiDeviceTokenRouteImport.update({
  id: '/api/device/token',
  path: '/api/device/token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellDashboardIndexRoute = AppShellDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellDashboardApiRoute = AppShellDashboardApiRouteImport.update({
  id: '/dashboard/api',
  path: '/dashboard/api',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellDashboardBillingRoute =
  AppShellDashboardBillingRouteImport.update({
    id: '/dashboard/billing',
    path: '/dashboard/billing',
    getParentRoute: () => AppShellRoute,
  } as any)
const AppShellDashboardLicensesRoute =
  AppShellDashboardLicensesRouteImport.update({
    id: '/dashboard/licenses',
    path: '/dashboard/licenses',
    getParentRoute: () => AppShellRoute,
  } as any)
const AppShellDashboardApiConvertRoute =
  AppShellDashboardApiConvertRouteImport.update({
    id: '/dashboard/api_/convert',
    path: '/dashboard/api/convert',
    getParentRoute: () => AppShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/device': typeof AppDeviceRoute
  '/changelog': typeof SiteChangelogRoute
  '/contact': typeof SiteContactRoute
  '/download': typeof SiteDownloadRoute
  '/formats': typeof SiteFormatsRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/checkout/desktop': typeof CheckoutDesktopRoute
  '/checkout/pro': typeof CheckoutProRoute
  '/updates/manifest.json': typeof UpdatesManifestDotjsonRoute
  '/account': typeof AppShellAccountRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/sign-in/verify': typeof AppSignInVerifyRoute
  '/sign-in/verify-email': typeof AppSignInVerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/cloud': typeof ApiDeviceCloudRoute
  '/api/device/license': typeof ApiDeviceLicenseRoute
  '/api/device/sign-out': typeof ApiDeviceSignOutRoute
  '/api/device/token': typeof ApiDeviceTokenRoute
  '/sign-in/': typeof AppSignInIndexRoute
  '/dashboard/api': typeof AppShellDashboardApiRoute
  '/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/dashboard/': typeof AppShellDashboardIndexRoute
  '/dashboard/api/convert': typeof AppShellDashboardApiConvertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/device': typeof AppDeviceRoute
  '/changelog': typeof SiteChangelogRoute
  '/contact': typeof SiteContactRoute
  '/download': typeof SiteDownloadRoute
  '/formats': typeof SiteFormatsRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/checkout/desktop': typeof CheckoutDesktopRoute
  '/checkout/pro': typeof CheckoutProRoute
  '/updates/manifest.json': typeof UpdatesManifestDotjsonRoute
  '/account': typeof AppShellAccountRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/sign-in/verify': typeof AppSignInVerifyRoute
  '/sign-in/verify-email': typeof AppSignInVerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/cloud': typeof ApiDeviceCloudRoute
  '/api/device/license': typeof ApiDeviceLicenseRoute
  '/api/device/sign-out': typeof ApiDeviceSignOutRoute
  '/api/device/token': typeof ApiDeviceTokenRoute
  '/sign-in': typeof AppSignInIndexRoute
  '/dashboard/api': typeof AppShellDashboardApiRoute
  '/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/dashboard': typeof AppShellDashboardIndexRoute
  '/dashboard/api/convert': typeof AppShellDashboardApiConvertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/brand': typeof BrandRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/_shell': typeof AppShellRouteWithChildren
  '/_app/device': typeof AppDeviceRoute
  '/_site/changelog': typeof SiteChangelogRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/download': typeof SiteDownloadRoute
  '/_site/formats': typeof SiteFormatsRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/checkout/desktop': typeof CheckoutDesktopRoute
  '/checkout/pro': typeof CheckoutProRoute
  '/updates/manifest.json': typeof UpdatesManifestDotjsonRoute
  '/_app/_shell/account': typeof AppShellAccountRoute
  '/_app/checkout/success': typeof AppCheckoutSuccessRoute
  '/_app/sign-in/check-email': typeof AppSignInCheckEmailRoute
  '/_app/sign-in/verify': typeof AppSignInVerifyRoute
  '/_app/sign-in/verify-email': typeof AppSignInVerifyEmailRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/device/cloud': typeof ApiDeviceCloudRoute
  '/api/device/license': typeof ApiDeviceLicenseRoute
  '/api/device/sign-out': typeof ApiDeviceSignOutRoute
  '/api/device/token': typeof ApiDeviceTokenRoute
  '/_app/sign-in/': typeof AppSignInIndexRoute
  '/_app/_shell/dashboard/api': typeof AppShellDashboardApiRoute
  '/_app/_shell/dashboard/billing': typeof AppShellDashboardBillingRoute
  '/_app/_shell/dashboard/licenses': typeof AppShellDashboardLicensesRoute
  '/_app/_shell/dashboard/': typeof AppShellDashboardIndexRoute
  '/_app/_shell/dashboard/api_/convert': typeof AppShellDashboardApiConvertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/device'
    | '/changelog'
    | '/contact'
    | '/download'
    | '/formats'
    | '/privacy'
    | '/terms'
    | '/checkout/desktop'
    | '/checkout/pro'
    | '/updates/manifest.json'
    | '/account'
    | '/checkout/success'
    | '/sign-in/check-email'
    | '/sign-in/verify'
    | '/sign-in/verify-email'
    | '/api/auth/$'
    | '/api/device/cloud'
    | '/api/device/license'
    | '/api/device/sign-out'
    | '/api/device/token'
    | '/sign-in/'
    | '/dashboard/api'
    | '/dashboard/billing'
    | '/dashboard/licenses'
    | '/dashboard/'
    | '/dashboard/api/convert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/device'
    | '/changelog'
    | '/contact'
    | '/download'
    | '/formats'
    | '/privacy'
    | '/terms'
    | '/checkout/desktop'
    | '/checkout/pro'
    | '/updates/manifest.json'
    | '/account'
    | '/checkout/success'
    | '/sign-in/check-email'
    | '/sign-in/verify'
    | '/sign-in/verify-email'
    | '/api/auth/$'
    | '/api/device/cloud'
    | '/api/device/license'
    | '/api/device/sign-out'
    | '/api/device/token'
    | '/sign-in'
    | '/dashboard/api'
    | '/dashboard/billing'
    | '/dashboard/licenses'
    | '/dashboard'
    | '/dashboard/api/convert'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_site'
    | '/brand'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/_shell'
    | '/_app/device'
    | '/_site/changelog'
    | '/_site/contact'
    | '/_site/download'
    | '/_site/formats'
    | '/_site/privacy'
    | '/_site/terms'
    | '/checkout/desktop'
    | '/checkout/pro'
    | '/updates/manifest.json'
    | '/_app/_shell/account'
    | '/_app/checkout/success'
    | '/_app/sign-in/check-email'
    | '/_app/sign-in/verify'
    | '/_app/sign-in/verify-email'
    | '/api/auth/$'
    | '/api/device/cloud'
    | '/api/device/license'
    | '/api/device/sign-out'
    | '/api/device/token'
    | '/_app/sign-in/'
    | '/_app/_shell/dashboard/api'
    | '/_app/_shell/dashboard/billing'
    | '/_app/_shell/dashboard/licenses'
    | '/_app/_shell/dashboard/'
    | '/_app/_shell/dashboard/api_/convert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  BrandRoute: typeof BrandRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutDesktopRoute: typeof CheckoutDesktopRoute
  CheckoutProRoute: typeof CheckoutProRoute
  UpdatesManifestDotjsonRoute: typeof UpdatesManifestDotjsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeviceCloudRoute: typeof ApiDeviceCloudRoute
  ApiDeviceLicenseRoute: typeof ApiDeviceLicenseRoute
  ApiDeviceSignOutRoute: typeof ApiDeviceSignOutRoute
  ApiDeviceTokenRoute: typeof ApiDeviceTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell': {
      id: '/_app/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/changelog': {
      id: '/_site/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof SiteChangelogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/download': {
      id: '/_site/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof SiteDownloadRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/formats': {
      id: '/_site/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof SiteFormatsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/checkout/desktop': {
      id: '/checkout/desktop'
      path: '/checkout/desktop'
      fullPath: '/checkout/desktop'
      preLoaderRoute: typeof CheckoutDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pro': {
      id: '/checkout/pro'
      path: '/checkout/pro'
      fullPath: '/checkout/pro'
      preLoaderRoute: typeof CheckoutProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/manifest.json': {
      id: '/updates/manifest.json'
      path: '/updates/manifest.json'
      fullPath: '/updates/manifest.json'
      preLoaderRoute: typeof UpdatesManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/account': {
      id: '/_app/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppShellAccountRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/checkout/success': {
      id: '/_app/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AppCheckoutSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in/': {
      id: '/_app/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AppSignInIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in/check-email': {
      id: '/_app/sign-in/check-email'
      path: '/sign-in/check-email'
      fullPath: '/sign-in/check-email'
      preLoaderRoute: typeof AppSignInCheckEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in/verify': {
      id: '/_app/sign-in/verify'
      path: '/sign-in/verify'
      fullPath: '/sign-in/verify'
      preLoaderRoute: typeof AppSignInVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in/verify-email': {
      id: '/_app/sign-in/verify-email'
      path: '/sign-in/verify-email'
      fullPath: '/sign-in/verify-email'
      preLoaderRoute: typeof AppSignInVerifyEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/cloud': {
      id: '/api/device/cloud'
      path: '/api/device/cloud'
      fullPath: '/api/device/cloud'
      preLoaderRoute: typeof ApiDeviceCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/license': {
      id: '/api/device/license'
      path: '/api/device/license'
      fullPath: '/api/device/license'
      preLoaderRoute: typeof ApiDeviceLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/sign-out': {
      id: '/api/device/sign-out'
      path: '/api/device/sign-out'
      fullPath: '/api/device/sign-out'
      preLoaderRoute: typeof ApiDeviceSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/token': {
      id: '/api/device/token'
      path: '/api/device/token'
      fullPath: '/api/device/token'
      preLoaderRoute: typeof ApiDeviceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_shell/dashboard/': {
      id: '/_app/_shell/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppShellDashboardIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/api': {
      id: '/_app/_shell/dashboard/api'
      path: '/dashboard/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof AppShellDashboardApiRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/billing': {
      id: '/_app/_shell/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AppShellDashboardBillingRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/licenses': {
      id: '/_app/_shell/dashboard/licenses'
      path: '/dashboard/licenses'
      fullPath: '/dashboard/licenses'
      preLoaderRoute: typeof AppShellDashboardLicensesRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_app/_shell/dashboard/api_/convert': {
      id: '/_app/_shell/dashboard/api_/convert'
      path: '/dashboard/api/convert'
      fullPath: '/dashboard/api/convert'
      preLoaderRoute: typeof AppShellDashboardApiConvertRouteImport
      parentRoute: typeof AppShellRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellAccountRoute: typeof AppShellAccountRoute
  AppShellDashboardApiRoute: typeof AppShellDashboardApiRoute
  AppShellDashboardBillingRoute: typeof AppShellDashboardBillingRoute
  AppShellDashboardLicensesRoute: typeof AppShellDashboardLicensesRoute
  AppShellDashboardIndexRoute: typeof AppShellDashboardIndexRoute
  AppShellDashboardApiConvertRoute: typeof AppShellDashboardApiConvertRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellAccountRoute: AppShellAccountRoute,
  AppShellDashboardApiRoute: AppShellDashboardApiRoute,
  AppShellDashboardBillingRoute: AppShellDashboardBillingRoute,
  AppShellDashboardLicensesRoute: AppShellDashboardLicensesRoute,
  AppShellDashboardIndexRoute: AppShellDashboardIndexRoute,
  AppShellDashboardApiConvertRoute: AppShellDashboardApiConvertRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

interface AppRouteChildren {
  AppShellRoute: typeof AppShellRouteWithChildren
  AppDeviceRoute: typeof AppDeviceRoute
  AppCheckoutSuccessRoute: typeof AppCheckoutSuccessRoute
  AppSignInCheckEmailRoute: typeof AppSignInCheckEmailRoute
  AppSignInVerifyRoute: typeof AppSignInVerifyRoute
  AppSignInVerifyEmailRoute: typeof AppSignInVerifyEmailRoute
  AppSignInIndexRoute: typeof AppSignInIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppShellRoute: AppShellRouteWithChildren,
  AppDeviceRoute: AppDeviceRoute,
  AppCheckoutSuccessRoute: AppCheckoutSuccessRoute,
  AppSignInCheckEmailRoute: AppSignInCheckEmailRoute,
  AppSignInVerifyRoute: AppSignInVerifyRoute,
  AppSignInVerifyEmailRoute: AppSignInVerifyEmailRoute,
  AppSignInIndexRoute: AppSignInIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteRouteChildren {
  SiteChangelogRoute: typeof SiteChangelogRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDownloadRoute: typeof SiteDownloadRoute
  SiteFormatsRoute: typeof SiteFormatsRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteChangelogRoute: SiteChangelogRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDownloadRoute: SiteDownloadRoute,
  SiteFormatsRoute: SiteFormatsRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  BrandRoute: BrandRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutDesktopRoute: CheckoutDesktopRoute,
  CheckoutProRoute: CheckoutProRoute,
  UpdatesManifestDotjsonRoute: UpdatesManifestDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeviceCloudRoute: ApiDeviceCloudRoute,
  ApiDeviceLicenseRoute: ApiDeviceLicenseRoute,
  ApiDeviceSignOutRoute: ApiDeviceSignOutRoute,
  ApiDeviceTokenRoute: ApiDeviceTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
