// Writes content/reference/formats.mdx from the capability list the API itself checks
// against (crates/convt-server/cloud-formats.json), so the page cannot drift from it.
type CloudFormat = {
  id: string;
  name: string;
  category: string;
  extensions: string[];
  mime: string;
  targets: string[];
};

const source = new URL("../../../crates/convt-server/cloud-formats.json", import.meta.url);
const destination = new URL("../content/reference/formats.mdx", import.meta.url);

const { formats } = (await Bun.file(source).json()) as { formats: CloudFormat[] };
if (!Array.isArray(formats) || formats.length === 0) throw new Error("No cloud formats found");

const categories: [string, string][] = [
  ["image", "Images"],
  ["vector", "Vector"],
  ["pdf", "PDF"],
  ["document", "Documents"],
  ["spreadsheet", "Spreadsheets"],
  ["presentation", "Presentations"],
  ["video", "Video"],
  ["audio", "Audio"],
];
const unknown = formats.filter((f) => !categories.some(([id]) => id === f.category));
if (unknown.length > 0)
  throw new Error(
    `Unlisted categories: ${[...new Set(unknown.map((f) => f.category))].join(", ")}`,
  );

const code = (value: string) => `\`${value}\``;
const sections = categories
  .map(([id, title]) => {
    const rows = formats
      .filter((f) => f.category === id)
      .map(
        (f) =>
          `| ${f.name} | ${code(f.id)} | ${f.extensions.map((e) => `.${e}`).join(", ")} | ${f.targets.map(code).join(", ")} |`,
      );
    if (rows.length === 0) return "";
    return [
      `## ${title}`,
      "",
      "| Format | `id` | Extensions | Converts to |",
      "| --- | --- | --- | --- |",
      ...rows,
      "",
    ].join("\n");
  })
  .filter(Boolean)
  .join("\n");

const page = `---
title: Formats
description: Every input format the convt API accepts and the targets each one converts to.
---

{/* Generated by scripts/generate-formats.ts from crates/convt-server/cloud-formats.json. Do not edit. */}

Use the \`id\` column for \`input_format\` and \`target_format\` when you [create a job](/api/jobs/reserve-job). The API accepts ${formats.length} input formats. A pair not listed here fails with \`400 unsupported_format\`.

\`GET /v1/formats\` returns every format convt recognizes, including some the cloud cannot convert to. This table is the list the API checks against.

${sections}`;

await Bun.write(destination, page);
console.log(`formats.mdx: ${formats.length} formats`);
