// The CLI gets this list from convt_core::FORMATS through default_registry().
const root = new URL("../../../", import.meta.url).pathname;
const proc = Bun.spawn([`${root}target/debug/convt`, "formats", "--json"], {
  stdout: "pipe",
  stderr: "inherit",
});
const raw = await new Response(proc.stdout).json();
if (await proc.exited) throw new Error("convt formats failed");
const formats = Array.isArray(raw) ? raw : raw.formats;
await Bun.write(
  new URL("../src/formats.ts", import.meta.url),
  `// Generated by bun run generate from convt formats --json.\nexport const formats = ${JSON.stringify(formats, null, 2)} as const;\nexport type Format = (typeof formats)[number]["id"];\n`,
);
